# Generated by Django 4.2.13 on 2024-05-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cnic', models.CharField(default='Nothing', max_length=100, unique=True)),
                ('phone', models.CharField(max_length=100, unique=True)),
                ('standard', models.CharField(blank=True, max_length=30, null=True)),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('ADMIN', 'Admin')], max_length=20)),
                ('address', models.TextField(default='Address')),
                ('created_at', models.DateTimeField(default='Now')),
            ],
        ),
    ]
