# Generated by Django 4.2.13 on 2024-05-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_address_alter_user_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='Password', max_length=100),
        ),
    ]
