# Generated by Django 4.2.13 on 2024-05-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='None', max_length=254, unique=True),
        ),
    ]
