# Generated by Django 4.2.13 on 2024-05-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanbook',
            name='fine',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
