# Generated by Django 4.2.13 on 2024-05-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
                ('publish_date', models.DateField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LOANED', 'Loaned')], max_length=200)),
                ('image', models.ImageField(upload_to='books')),
            ],
            options={
                'unique_together': {('title', 'author')},
            },
        ),
    ]
